import type { NextPage } from "next";
import Head from "next/head";
import Post from "../components/Post";
import styles from "../styles/Home.module.css";
import { Flex, Box } from "@chakra-ui/react";

const titles = {
  post1: `Poprzednia dekada nalezala do Drake'a. Jak Kanadyjczyk wplynal na muzyke popularna?`,
};

const authors = {
  author1: `Piotr Żelazny`,
};

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>newonce_task_JB</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Flex position="absolute" direction="column" alignItems="center" p="2px">
        <Post
          imageUrl="/rihanna.svg"
          tagName="HIP-HOP"
          title={titles.post1}
          author={authors.author1}
          createdAt={"1 godz. temu"}
        />
      </Flex>
    </div>
  );
};

export default Home;
